@extends('layouts.doc-page')
@section('title', "API Token")
@section('sidebar')
<ul class="section-items list-unstyled nav flex-column pb-3">
    <li class="nav-item section-title"><a class="nav-link scrollto active" href="#section-1"><span
                class="theme-icon-holder me-2"><i class="fa-solid fa-tower-broadcast"></i></span>API Token</a>
    </li>
    <li class="nav-item"><a class="nav-link scrollto" href="#item-1-1">Api Token Tutorial</a></li>
    <li class="nav-item"><a class="nav-link scrollto" href="#item-1-2">Generate Token</a></li>
    <li class="nav-item"><a class="nav-link scrollto" href="#item-1-3">Revoke Token</a></li>
</ul>
@endsection
@section('content')
<article class="docs-article" id="section-1">
    <header class="docs-header">
       <h1 class="docs-heading">API Token <span class="docs-time">Last updated: 2023-02-17</span>
        </h1>
        <section class="docs-intro">
            <p>SendEach application allows for the generation of API token to connect your third-party applicationw with our server and consume API resources.</p>
        </section>
        <!--//docs-intro-->
    </header>
    <section class="docs-section" id="item-1-1">
        <h2 class="section-heading">Api Token Creating Tutorial</h2>
        <video class="img-fluid " controls>
            <source src="\assets\docs\images\doc-pages/Api_toke_create_tutorial.mp4" type="video/mp4">
        </video>
    </section>
    <section class="docs-section" id="item-1-2">
        <h2 class="section-heading">Generate Token</h2>
        <div class="mb-5">
            <p class="h5">1. Click on your profile Image(In the top right corner) and select the API Tokens option</p>
            <img src="/assets/docs/images/doc-pages/5-logout or apitoken.png" alt="login" class="img-fluid mt-2 border">
        </div>
        <div class="mb-5">
            <p class="h5">2. Click the + button (In the bottom right corner) to generate API Token</p>
            <img src="/assets/docs/images/doc-pages/6-generate-Apitoken.png" alt="login" class="img-fluid mt-2 border">
        </div>
        <div class="mb-5">
            <p class="h5">3. Enter the name for API token in the popup and click on Submit button</p>
            <img src="/assets/docs/images/doc-pages/7-enter-name.png" alt="login" class="img-fluid mt-2 border">
        </div>
        <div class="">
            <p class="h5">4. Your generated api token will be shown in the new popup</p>
            <div class="alert alert-info mt-2">
                <p>Make sure you save the generated API token in a safe place as you will only
                    see this token once.</p>
            </div>
            <img src="/assets/docs/images/doc-pages/8-token.png" alt="login" class="img-fluid mt-2 border">
        </div>
        <!--//docs-code-block-->
    </section>
    <!--//section-->

    <section class="docs-section" id="item-1-3">
        <h2 class="section-heading">Revoke Token</h2>

        <div class="mb-5">
            <p class="h5">1. Click on your profile Image(In the top right corner) and select the API Tokens option</p>
            <img src="/assets/docs/images/doc-pages/5-logout or apitoken.png" alt="login" class="img-fluid mt-2 border">
        </div>
        <div class="mb-5">
            <p class="h5">2. You will see a list of tokens that were previously generated by you.
                <br>To revoke a token click on the delete button of that token row.</p>
            <img src="/assets/docs/images/doc-pages/9-delete-token.png" alt="login" class="img-fluid mt-2 border">
        </div>
        <div class="mb-5">
            <p class="h5">3. Click on confirm delete to begin the delete process.</p>
            <div class="alert alert-danger">
                <em>Caution: This action is no-reversible, so make sure you understand what you're doing.</em>
            </div>
            <img src="/assets/docs/images/doc-pages/10-alert-delete.png" alt="login" class="img-fluid mt-2 border">
        </div>
        <div>
            <p class="h5">4. After the successful deletion of the token, you will see a success message on the top right corner.</p>
            <img src="/assets/docs/images/doc-pages/11-token-deleted.png" alt="login" class="img-fluid mt-2 border">
        </div>
    </section>
    <!--//section-->

</article>
<!--//docs-article-->
@endsection
